apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
spec:
  replicas: 0
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: sample
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
          resources:
            requests:
              cpu: 1
