apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: provisioner3
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot", "on-demand"]
    - key: topology.kubernetes.io/zone
      operator: In
      values: ["ap-southeast-1c"] # Asia Pacific (Osaka)
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"]
    - key: node.kubernetes.io/instance-type
      operator: In
      values: ["g4dn.xlarge", "g4dn.12xlarge"]
  limits:
    resources:
      cpu: 700m00
      memory: 1000Gi
  provider:
    subnetSelector:
      karpenter.sh/discovery: karpenter-tidu
    securityGroupSelector:
      karpenter.sh/discovery: karpenter-tidu
  ttlSecondsAfterEmpty: 10
